<a href="https://colab.research.google.com/github/DevT3e/April-29th/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
text_data = [" Interrobang. By Aishwarya Henriette ",
"Parking And Going. By Karl Gautier", "Today Is The night. By Jarek Prakash" ]
strip_whitespace = [string.strip() for string in text_data]
# Показать текст
strip_whitespace
# Удалить точки
remove_periods = [string.replace(".", "") for string in strip_whitespace]
# Показать текст
remove_periods
# Создать функцию
def capitalizer(string: str) -> str:
 return string.upper()
# Применить функцию
[capitalizer(string) for string in remove_periods]
# Импортировать библиотеку
import re
# Создать функцию
def replace_letters_with_X(string: str) -> str:
 return re.sub(r"[a-zA-Z]", "X", string)
 # Применить функцию
[replace_letters_with_X(string) for string in remove_periods]

['XXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX',
 'XXXXXXX XXX XXXXX XX XXXX XXXXXXX',
 'XXXXX XX XXX XXXXX XX XXXXX XXXXXXX']

In [121]:
# Загрузить библиотеку
from bs4 import BeautifulSoup
# Создать немного кода с разметкой HTML


SyntaxError: ignored

In [40]:
# Загрузить библиотеки
import unicodedata
import sys
# Создать текст
text_data = [ 'Hi !!!! I. Love. This. Song....',
'40000% Agree! !! ! #LoveIT',
'Right?!?!']
# Создать словарь знаков препинания
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
if unicodedata.category(chr(i)).startswith('P'))
# Удалить любые знаки препинания во всех строковых значениях
[string.translate(punctuation) for string in text_data]
['Hi I Love This Song', '10000 Agree LovelT', 'Right']

['Hi I Love This Song', '10000 Agree LovelT', 'Right']

In [50]:
import nltk
# Загрузить библиотеку
from nltk.tokenize import word_tokenize
# Создать текст
string = "Сегодняшняя наука — это технология завтрашнего дня"


In [66]:
# Загрузить библиотеку
from nltk.corpus import stopwords
# Перед этим вам следует скачать набор стоп-слов
import nltk
nltk.download('stopwords')
# Создать лексеьш слов
tokenized_words = ['i', 'am', 'going', 'to','go', 'to', 'the', 'store', 'and', 'park']
# Загрузить стоп-слова
stop_words = stopwords.words('english')
# Удалить стоп-слова
[word for word in tokenized_words if word not in stop_words]
['going', 'go', 'store', 'park']
stop_list = stopwords.words('russian')
# Создать словарные лексемы
tokenized_words = ['я','бы', 'пошел', 'в', 'пиццерию', 'покушать', 'пиццы', 'и', 'потом', 'В', 'парк']
# Загрузить стоп-слова
stop_words = stopwords.words('russian')
# Удалить стоп-слова
[word for word in tokenized_words if word not in stop_words]
['пошел', 'пиццерию', 'покушать', 'пиццы', 'парк']
# Удалить стоп-слова
stop_words[:5]
['i ', 'me', 'my', 'myself', 'we']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i ', 'me', 'my', 'myself', 'we']

In [76]:
# Загрузить библиотеку
from nltk.stem.porter import PorterStemmer
# Создать лексемы слов
tokenized_words = ['i ', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']
# Создать стеммер
porter = PorterStemmer()
# Применить стеммер
[porter.stem(word) for word in tokenized_words]
# Загрузить библиотеку
from nltk.stem.snowball import SnowballStemmer
# Создать лексемы слов
tokenized_words = ['рыбаки', 'рыбаков', 'рыбаками']
# Создать стеммер
snowball = SnowballStemmer("russian")
# Применить стеммер
[snowball.stem(word) for word in tokenized_words]


['рыбак', 'рыбак', 'рыбак']

In [84]:
# Загрузить библиотеку
from nltk.stem import WordNetLemmatizer
# Создать лексемы слов
tokenized_words = ['go', 'went', 'gone', 'am', 'are', 'is', 'was', 'were']
# Создать лемматизатор
lemmatizer = WordNetLemmatizer()


In [89]:
# Загрузить библиотеки
from nltk import pos_tag
from nltk import word_tokenize
# Создать текст
text_data = "Chris loved outdoor running"
# Использовать предварительно натренированный


In [104]:
# Загрузить библиотеки
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
# Создать текст
text_data = np.array(['Бразилия — моя любовь. Бразилия!',
'Швеция — лучше',
'Германия бьет обоих'])
# Создать матрицу признаков на основе мешка слов
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)
# Показать матрицу признаков
print(bag_of_words.toarray())


[[2 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0 1]
 [0 1 1 0 0 0 1 0]]


In [115]:
# Загрузить библиотеки
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
# Создать текст
text_data = np.array (['Бразилия - моя любовь. Бразилия!','Швеция — лучше', 'Германия бьет обоих'])
# Создать матрицу признаков на основе меры tf-idf
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)
# Показать матрицу признаков на основе меры tf-idf
print(feature_matrix.toarray())
# Показать имена признаков
tfidf.vocabulary_
{'бразилия': 0,
'бьет': 1,
'германия': 2,
'лучше': 3,
'любовь': 4,
'моя' : 5,
'обоих': 6,
'Швеция': 7}

[[0.81649658 0.         0.         0.         0.40824829 0.40824829
  0.         0.        ]
 [0.         0.         0.         0.70710678 0.         0.
  0.         0.70710678]
 [0.         0.57735027 0.57735027 0.         0.         0.
  0.57735027 0.        ]]


{'бразилия': 0,
 'бьет': 1,
 'германия': 2,
 'лучше': 3,
 'любовь': 4,
 'моя': 5,
 'обоих': 6,
 'Швеция': 7}